apiVersion: v2
name: api
description: A Helm chart for Pages API
type: application
version: 0.1.0
appVersion: "1.0"



apiVersion: v2
name: pages-api
description: A Helm chart for Pages API backend service
type: application
version: 1.0.0
appVersion: "1.0"